name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      indexName:
        description: "Name of the index to build"
        required: true
        type: choice
        options:
          - posit-search-dev
          - posit-search
#permissions:
#  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    #permissions:
    #  pull-requests: write
    #  actions: write
    #  contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # python ----
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Upload dev index
        run: |
          uv run 0-merge-search.py
          uv run 1-upload-index.py
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY_WRITE: ${{ secrets.ALGOLIA_API_KEY_WRITE }}

      # NOTE: no longer build quarto site, now using a shiny app
      #       on connect cloud
      # quarto docs build ----
      #- uses: quarto-dev/quarto-actions/setup@v2

      #- name: Build docs
      #  run: |
      #    cd docs
      #    quarto render
      #    cp search.json _site/search.json

      #- name: Deploy
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  if: ${{ github.ref == 'refs/heads/main' }}
      #  with:
      #    force: false
      #    folder: docs/_site
      #    clean-exclude: pr-preview

      #- name: Deploy (preview)
      #  uses: rossjrw/pr-preview-action@v1
      #  # if in a PR
      #  if: ${{ github.event_name == 'pull_request' }}
      #  with:
      #    source-dir: docs/_site
